### ISSUE TITLE
Website Tasks

### ISSUE THREAD

**Issue by 11155987** [11155987/11155987.github.io#1]
Add pictures to Homepage

**Comment by 11155987** [comment]
Add text content to Homepage

**Comment by 11155987** [comment]
Change title for each page

**Comment by 11155987** [comment]
Change links appear at the top in the Clothing page

**Comment by 11155987** [comment]
Change links to appear at the top in the Feet page

**Comment by jhawlc** [comment]
https://classroom.google.com/c/NTQ5OTYzMzU0NzU4/m/NjA2NTM3MjEyNDEy/details

**Comment by jhawlc** [comment]
These should be separate issues
